language: erlang
otp_release:
  - 19.1
script: asdf plugin-test lfe https://github.com/vic/asdf-lfe.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
